import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Components/__organisms/Navbar/Navbar";

const inter = Inter({
  subsets: ["greek"],
  weight: ["100", "300", "400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#FAFAFA] `}
      >
        <Navbar/>
        <div className="px-6">
          {children}
        </div>
      </body>
    </html>
  );
}
