import type { Metadata } from "next";
import "./globals.css";
<<<<<<< HEAD
import { Instrument_Sans } from "next/font/google";
import { Inter } from "next/font/google";
=======
import Navbar from "./Components/__organisms/Navbar/Navbar";
>>>>>>> efee61df5b4d445b0d79fb0d0bc0e77f4f56dfb3

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
  variable: "--font-instrument-sans",
});

const inter = Inter({
  subsets: ["greek"],
  weight: ["100", "300", "400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FAFAFA]`}
      >
        <Navbar/>
        {children}
      </body>
>>>>>>> efee61df5b4d445b0d79fb0d0bc0e77f4f56dfb3
    </html>
  );
}
